### ISSUE TITLE
Koordinat penang detect as Johor?

### ISSUE THREAD

**Issue by thaqiif** [MalaysiaPrayerTimes/provider#6]
Assalamualaikum. Saya confuse. Kenapa koordinat negeri penang, resultnya kawasan johor?

![image](https://user-images.githubusercontent.com/6726320/36351851-46fbc294-14ea-11e8-8716-c04f0404d1a7.png)

Terima kasih.

**Comment by i906** [comment]
Terima kasih, isu ini sudah diperbaiki.
